### ISSUE TITLE
example async() await format

### ISSUE THREAD

**Issue by mhaley-ee** [rogierschouten/async-lock#20]
[async-lock-example.zip](https://github.com/rogierschouten/async-lock/files/2824049/async-lock-example.zip)

**Comment by mhaley-ee** [comment]
Please consider presenting a version of this for the others that want to use this module.

The source needs to be scrubbed to remove require('moment') so unfortunate that's in there.

-Mike

**Comment by mhaley-ee** [comment]
Please this is the third try with my crappy webrowser it seems like something is going wrong.

**Comment by rogierschouten** [comment]
Hi @mhaley-ee , thank you for trying to make async-lock more understandable.  I took over maintenance of this module when the original creator disappeared.  Right now, I'm no longer using it myself, so I limit myself to merging PRs. Would you please send a PR with an adjusted README.md?

**Comment by rogierschouten** [comment]
closing because no PR forthcoming

**Comment by windsome** [comment]
> Hi @mhaley-ee , thank you for trying to make async-lock more understandable. I took over maintenance of this module when the original creator disappeared. Right now, I'm no longer using it myself, so I limit myself to merging PRs. Would you please send a PR with an adjusted README.md?

why no longer use this? is there a better choice?
