### ISSUE TITLE
ES5 compliance requested

### ISSUE THREAD

**Issue by igabesz** [rogierschouten/async-lock#21]
We use this package in a browser, and we have a problem with the build: the package uses arrow functions that are not ES compliant. 

Temporarily we solved the issue by adding the path `"node_modules/async-lock/**/*.js"` to our tsconfig path (plus `allowJs: true`) but it's rather a hack than a real solution. 

I see the arrow function in 2 lines which could be changed to a simple function without a problem. (I did not check for anything else that is not ES5 compliant.)

- [Line 52](https://github.com/rogierschouten/async-lock/blob/master/lib/index.js#L52)
- [Line 212](https://github.com/rogierschouten/async-lock/blob/master/lib/index.js#L212)

We have no problem with Promises and other things that can be polyfilled.

**Comment by rogierschouten** [comment]
Sure, seems a fair request. For reasons outlined in almost every other issue here I don't make changes myself but I'll happily merge a PR for you

**Comment by rogierschouten** [comment]
Fixed in v1.2.0. Thank you @paulroub !
