### ISSUE TITLE
Please remove grunt-env

### ISSUE THREAD

**Issue by LosTigeros** [rogierschouten/async-lock#25]
grunt-env is pretty old and shows vulnerabilities on `npm audit`. It wasn't like that when it was a dev-dependency.
![image](https://user-images.githubusercontent.com/6253928/61245010-d6d24100-a74b-11e9-97ad-2c3150b88361.png)

**Comment by rogierschouten** [comment]
Oops, my bad.  Will release asap.

**Comment by rogierschouten** [comment]
v1.2.2 released
