### ISSUE TITLE
Remove Q dependency

### ISSUE THREAD

**Issue by erikvold** [rogierschouten/async-lock#3]
Seems like the `Promise` global is pretty standard now, it would be nice if that were used as the default instead of Q, and so that this package has no dependencies.

**Comment by rogierschouten** [comment]
Yes I thought about that. It would need a major version increase. I also could not quickly figure out how to test for the global in every environment that the original author of this module took into account. It should not be a big hurdle though.  Any chance of getting a PR on this? This isn't even my module - got ownership after the owner went silent and a bug needed fixing - so I'd appreciate the rest of the community also helping out.

**Comment by rogierschouten** [comment]
... and the PR just came in. Thx ;)

**Comment by rogierschouten** [comment]
Solution published as v1.0.0. Thanks @erikvold !

**Comment by erikvold** [comment]
https://github.com/rogierschouten/async-lock/commit/533b4300211f600ee0c180e6c361692d3522f2ec
