### ISSUE TITLE
How long does a lock last?

### ISSUE THREAD

**Issue by CHOMNANP** [rogierschouten/async-lock#31]
Just curious, how long does a lock last?

**Comment by rogierschouten** [comment]
Until you release it - depending on the interface you use, that is either by calling the provided callback ('done' in README.md) or by resolving a promise.

Closing this issue - please feel free to reopen if needed.

**Comment by CHOMNANP** [comment]
> Until you release it - depending on the interface you use, that is either by calling the provided callback ('done' in README.md) or by resolving a promise.
> 
> Closing this issue - please feel free to reopen if needed.

Is there a way to set lifetime of a queue?
Let say we want to create a queue and has a lifetime of 10 minute.
If the queue is not released within 10 minutes, then it will automatically release.

**Comment by rogierschouten** [comment]
...what would that do for the correctness of your program?  In fact then you' re not locking queues. 

I guess you could implement that by calling the 'done' callback on a setTimeout()

**Comment by CHOMNANP** [comment]
> ...what would that do for the correctness of your program? In fact then you' re not locking queues.
> 
> I guess you could implement that by calling the 'done' callback on a setTimeout()

I'm just thinking out loud. In my view, that would help prevent the dead-lock of the queue. Let say, the process has lock a queue, then someone decided to restart the application before the lock has been release. Then there will be a deadlock in the application.
