### ISSUE TITLE
MaxPending Infinity breaking change

### ISSUE THREAD

**Issue by coderaiser** [rogierschouten/async-lock#39]
`maxPending`can be [Inifinity](https://github.com/isomorphic-git/isomorphic-git/blob/v1.8.0/src/managers/GitIndexManager.js#L54) in [isomorphic-git](https://isomorphic-git.org/), for example. Would be great to keep support of it. One of possible solutions can be changing [Number.isInteger](https://github.com/rogierschouten/async-lock/blob/v1.2.5/lib/index.js#L19) into `!Number.isNaN`.

```js
this.maxPending = !Number.isNaN(opts.maxPending) ? opts.maxPending : AsyncLock.DEFAULT_MAX_PENDING;
```

**Comment by rogierschouten** [comment]
@coderaiser Thank you for reporting.   Fix published as v1.2.6

**Comment by rogierschouten** [comment]
Closing this issue, let me know if there is still any problem.  @bmrpatel looks like we broke something after all!

**Comment by coderaiser** [comment]
Thank you for such a quick fix 🥳
