### ISSUE TITLE
using `maxOccupationTime` in typescript not working

### ISSUE THREAD

**Issue by npomfret** [rogierschouten/async-lock#45]
`Error:(8, 40) TS2345: Argument of type '{ maxOccupationTime: number; }' is not assignable to parameter of type 'AsyncLockOptions'.
  Object literal may only specify known properties, and 'maxOccupationTime' does not exist in type 'AsyncLockOptions'.`

**Comment by rogierschouten** [comment]
@npomfret thank you for reporting. 

@abozaralizadeh and @ThePiz  are you willing to fix this? The TypeScript definitions need adjusting.

**Comment by abozaralizadeh** [comment]
Seems to be an unrelated issue to this package. it seems to be related to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) that uses async-lock & you've already figured it out here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52626

**Comment by rogierschouten** [comment]
Then I'll close it here, thanks
