### ISSUE TITLE
Is it ok to make lock.queues public knowledge?

### ISSUE THREAD

**Issue by Noitidart** [rogierschouten/async-lock#50]
I am working on a detecting if there are pending tasks on a queue, so I checked `lock.queues`. However we don't make this public knoweldge so it's implementation detail right now. Is it ok to pr to make this public and kind of a contract that we stick to?

**Comment by rogierschouten** [comment]
If I were you, I would maintain that in a separate variable. This package is rather hard to change (low code and test quality)

**Comment by Noitidart** [comment]
Thanks for your fast reply. So to do that I would have to maintain a queue of my own right?

**Comment by rogierschouten** [comment]
You'd have to maintain a map, not a queue. Otherwise you'd have to mimick async locks behavior exactly and you don't want that
