### ISSUE TITLE
Question: Locking across Heroku Dynos

### ISSUE THREAD

**Issue by joeschneider32** [rogierschouten/async-lock#60]
My Heroku App is running on multiple dynos. Is this package able to lock across dynos?

**Comment by rogierschouten** [comment]
I don't know. I only maintain the package because the author disappeared, and I did not have that use case.  In fact, the quality is so low and the code so unreadable that I would advise you not to use this at all.

**Comment by joeschneider32** [comment]
@rogierschouten , thanks for your feedback and for maintaining this package. I'll explore alternatives.
