### ISSUE TITLE
Usage with async/await

### ISSUE THREAD

**Issue by mykola-mokhnach** [rogierschouten/async-lock#7]
Hi,

I just wanted to make sure the lock will work as expected if one calls it this way:

```javascript
import AsyncLock from 'async-lock';

const lock = new AsyncLock();

async function bla () {
  await lock.acquire(bla.name, async () => {
     // some async stuff that should be executed in critical section
  });
}
```

**Comment by rogierschouten** [comment]
As far as I know anything that works with promises should work with async/await. If you want to be sure, you can always submit a PR with a couple of test cases if you like.
